--------------------------------------------------------
-- Archivo creado  - jueves-diciembre-03-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CRUD_TARJETAS_CREDITO
--------------------------------------------------------

  CREATE TABLE "CRISTHIAN"."CRUD_TARJETAS_CREDITO" 
   (	"NUM_ID_TARJETA" NUMBER(2,0), 
	"STR_NUMERO_TARJETA" VARCHAR2(16 BYTE), 
	"STR_TIPO_TARJETA" VARCHAR2(20 BYTE), 
	"DATE_FECHA_VENCIMIENTO" DATE, 
	"STR_CVV" VARCHAR2(3 BYTE), 
	"NUM_ID_CLIENTE" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CRUD_TARJETAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRISTHIAN"."CRUD_TARJETAS_PK" ON "CRISTHIAN"."CRUD_TARJETAS_CREDITO" ("NUM_ID_TARJETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CRUD_TARJETAS_CREDITO
--------------------------------------------------------

  ALTER TABLE "CRISTHIAN"."CRUD_TARJETAS_CREDITO" ADD CONSTRAINT "CRUD_TARJETAS_PK" PRIMARY KEY ("NUM_ID_TARJETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "CRISTHIAN"."CRUD_TARJETAS_CREDITO" MODIFY ("NUM_ID_TARJETA" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTHIAN"."CRUD_TARJETAS_CREDITO" MODIFY ("STR_NUMERO_TARJETA" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTHIAN"."CRUD_TARJETAS_CREDITO" MODIFY ("STR_TIPO_TARJETA" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTHIAN"."CRUD_TARJETAS_CREDITO" MODIFY ("DATE_FECHA_VENCIMIENTO" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTHIAN"."CRUD_TARJETAS_CREDITO" MODIFY ("STR_CVV" NOT NULL ENABLE);
 
  ALTER TABLE "CRISTHIAN"."CRUD_TARJETAS_CREDITO" MODIFY ("NUM_ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CRUD_TARJETAS_CREDITO
--------------------------------------------------------

  ALTER TABLE "CRISTHIAN"."CRUD_TARJETAS_CREDITO" ADD CONSTRAINT "TARJETAS_CLIENTES_FK" FOREIGN KEY ("NUM_ID_CLIENTE")
	  REFERENCES "CRISTHIAN"."CRUD_CLIENTES" ("NUM_ID_CLIENTE") ENABLE;
